{{- range .Values.apps }}    
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
spec:
  type: {{ .servicetype }}
  selector:
    name: {{ .name }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
---
{{- end }}